### ISSUE TITLE
Aftman does not install correctly if ~/.zshenv file does not exist (MacOS).

### ISSUE THREAD

**Issue by christopher-buss** [LPGhatguy/aftman#23]
Currently aftman will say that it has successfully installed, but if the ~/.zshenv is not present already then it will silently fail without warning as it cannot add it to the system path.

Preferably it should aggressively create this file that is required if it is needed, but at the very least should prompt the user if the file doesn't exist, that they should create it.

**Comment by Yumacide** [comment]
Aftman already logs at the debug level when PATH isn't modified; maybe this should be a warning instead?
