### ISSUE TITLE
Path with space makes it impossible to install

### ISSUE THREAD

**Issue by ATK422** [LPGhatguy/aftman#37]
Pretty much what the title says, if you have a space in your path (i. e. User).
For example, if it was "C:\Users\Hello World" then it would only say C:\Users\Hello

**Comment by LPGhatguy** [comment]
Hello, thanks for filing an issue!

Where are you having this issue? Are you using Aftman via the VS Code Rojo extension? What commands fail? What is the error message?

**Comment by LPGhatguy** [comment]
I believe this is likely an issue with the Rojo VS Code extension or some other place that involves running commands from strings. I don't believe that Aftman is directly involved in this issue.
