### ISSUE TITLE
aftman not recognized by UNIX terminal despite being in the /user path

### ISSUE THREAD

**Issue by MichelAguilera** [LPGhatguy/aftman#40]
I use MacOS X

-- Other stuff
drwxr-xr-x    9 user  staff    288 Dec  4 17:54 .aftman
-- Other stuff

% aftman --version
zsh: command not found: aftman

**Comment by LPGhatguy** [comment]
Hello, thanks for filing an issue!

This is an issue with your system's configuration, as Aftman does not affect how your shell resolves paths or runs programs. Aftman does try to modify your shell's startup scripts, so maybe restarting the shell would be enough.
