### ISSUE TITLE
MacOS aarch Release build is actually x86

### ISSUE THREAD

**Issue by thunn** [LPGhatguy/aftman#48]
When I download [aftman-0.2.7-macos-aarch64.zip](https://github.com/LPGhatguy/aftman/releases/download/v0.2.7/aftman-0.2.7-macos-aarch64.zip) from the v0.2.7 release page and run file on it I get `aftman: Mach-O 64-bit executable x86_64`

When I build it locally I am getting `aftman: Mach-O 64-bit executable arm64`

Can someone confirm this?

**Comment by filiptibell** [comment]
Yeah, the latest version was mistakenly built for x86 even for arm, it was solved in this PR: https://github.com/LPGhatguy/aftman/pull/34
Will require a new release of aftman which should then be built for the correct arch
