### ISSUE TITLE
`macos-x86_64` being installed instead of `macos-aarch64`

### ISSUE THREAD

**Issue by sasial-dev** [LPGhatguy/aftman#59]
I'm installing rojo `7.4.0`, and the wrong arch is installed for my system. Although `x86_64` is compatible via Rosetta 2, `aarch64` should be installed as the prefered binary

**Comment by jackTabsCode** [comment]
@sasial-dev  After building Aftman from source, I don't experience this issue anymore, but I still do with the released version. No clue what is going on but maybe you could test this as well?

**Comment by filiptibell** [comment]
@jackTabsCode it's because the latest release of Aftman on GitHub is not actually built for aarch64, so Aftman thinks its running on x86_64, check out this other duplicate issue: https://github.com/LPGhatguy/aftman/issues/48

**Comment by LPGhatguy** [comment]
Whoops, sorry, I didn't realize this was just waiting on me to cut a release. Been awhile since I've checked in!

Release going out ASAP.
