### ISSUE TITLE
Add `--fallible` flag to `aftman install`

### ISSUE THREAD

**Issue by nezuo** [LPGhatguy/aftman#6]
I use a private command line tool hosted on GitHub and would like to install it using aftman. This breaks my CI however, since it cannot install the tool. If there were a way to ignore installation errors or ignore specific tools it would solve my issue. The title API is just an example.

**Comment by nezuo** [comment]
It doesn't look like aftman has `aftman github-auth` so private CLIs aren't supported yet.

**Comment by LPGhatguy** [comment]
I think that adding authentication will help. I think we should also make `aftman install` try to install your other tools even if one of them fails, though. Right now, it gives up after the first error.
