### ISSUE TITLE
Run `Build (x86_64-unknown-linux-gnu)` job

### ISSUE THREAD

**Issue by DervexDev** [LPGhatguy/aftman#61]
This job is waiting to run for over 40 minutes now. This causes all GitHub workflows using [setup-aftman](https://github.com/ok-nick/setup-aftman) action to fail as it uses the latest tag by default.

**Comment by LPGhatguy** [comment]
Super cursed GitHub Actions issue. I just restarted the action to see if it'll actually run this time.

**Comment by DervexDev** [comment]
Yeah that's probably GitHub's fault. I had a very similar issue some time ago.

**Comment by filiptibell** [comment]
Looks like it isn't starting because it's requesting an `ubuntu-18.04` runner and waiting for one to become available. Those runners were removed some time ago: https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

**Comment by LPGhatguy** [comment]
Hah, cool. I'll see if I can patch a fix in without blowing things up too badly.

I remember we chose 18.04 specifically because of some funny libc/OpenSSL compat issues.

**Comment by DervexDev** [comment]
We could use `reqwest` with the `rustls-tls` feature. It builds just fine on `ubuntu-latest`.

**Comment by LPGhatguy** [comment]
For the time being, I've deleted the v0.2.8 release. The new action has created a new draft release that will go live when it's ready.

If someone wants to PR the rustls-tls feature change (it should be small!) I'm down to get that in a follow-up release.

**Comment by LPGhatguy** [comment]
Alright, this issue should be resolved for the v0.2.8 release.

**Comment by DervexDev** [comment]
Just opened #62
