### ISSUE TITLE
Incompatible with ""old"" versions of ubuntu

### ISSUE THREAD

**Issue by Furlanetto-Dev** [LPGhatguy/aftman#67]
```
./aftman: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./aftman)<br>
./aftman: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./aftman)<br>
./aftman: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./aftman)<br>
```

I'm using ubuntu 20.04 which uses libc verison 2.31, this might be a problem in my side though

**Comment by OverHash** [comment]
Yes, you need to upgrade your system if you want to use newer versions of `aftman`.

Alternatively you could build aftman from source.

**Comment by Furlanetto-Dev** [comment]
this sucks ubuntu 20.04 is still in LTS

**Comment by OverHash** [comment]
LTS doesn't mean all software works. It means your distribution is still maintaining that version.

But you didn't get aftman from Ubuntu (as an apt package), you got it as a download from GitHub. There's no support guarantee for that from Ubuntu.
