### ISSUE TITLE
Aftman not added to PATH and does not install packages

### ISSUE THREAD

**Issue by kolvian** [LPGhatguy/aftman#70]
Simply put, when running ./aftman self-install on the pre-compiled executable 0.3.0, the aftman command is not recognized and seemingly not added to PATH. In addition, trying to install using the pre-compiled executable does not install the desired packages, and seemingly does nothing.

**Comment by Errorbot1122** [comment]
Same here, it just never installs... I think the project is inactive tho...

**Comment by Errorbot1122** [comment]
Neverminded, I just had to restart.

**Comment by kolvian** [comment]
I also fixed it just by restarting. Still a bit of a bug but not critical.
